services:
  - type: web
    name: product-filler
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.main
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - requirements.txt
        - render.yaml
    healthCheckPath: /
    autoDeploy: true
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.main
      - key: FLASK_ENV
        value: production 